import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.Reader;
import java.lang.reflect.Type;
import java.util.List;
import java.util.Random;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {


    public static void main(String[] args) throws FileNotFoundException {
        Gson gson = new Gson();
        try(Reader reader = new FileReader("D:\\java_Course\\java-fundamentals\\quotes\\src\\main\\resources\\recentquotes.json")) {
            Type collectionType = new TypeToken<List<Quotes>>() {}.getType();

            List<Quotes> quotesList= gson.fromJson(reader,collectionType);

            /*for (Quotes quotes: quotesList) {
                System.out.println("The tags: "+ quotes.getTags().toString());
                System.out.println("The author: "+ quotes.getAuthor());
                System.out.println("The Likes: "+ quotes.getLikes());
                System.out.println("The text: "+ quotes.getText());
                System.out.println();
                System.out.println();
            }
*/
            System.out.println();
            Random rand = new Random();
            int randomIndex = rand.nextInt(quotesList.size());
            Quotes randomElement = quotesList.get(randomIndex);
            System.out.println("The author: "+ randomElement.getAuthor());
            System.out.println("The text: "+ randomElement.getText());
            System.out.println();
            System.out.println();

        } catch (IOException e) {
            e.printStackTrace();
            throw new RuntimeException(e);
        }
    }
}
